# Generated by Django 4.0.6 on 2022-07-19 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='유저이름')),
                ('age', models.IntegerField(default=0, verbose_name='유저나이')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('content', models.TextField(verbose_name='컨텐츠')),
                ('photo', models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='사진')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user')),
            ],
        ),
    ]
